 title: Ill-said thoughts
author: Josué Tonelli-Cueto
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Josué Tonelli-Cueto on random things. In English & Spanish.
theme: minima


# social links
twitter_username: tonellicueto # DO NOT include the @ character, or else the build will fail!
github_username:  tonellicueto # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
  - jekyll-feed

  minima:
  social_links:
    twitter: tonellicueto
    github: tonellicueto
    instagram: tonellicueto
    linkedin: tonellicueto

    youtube: tonellicueto
    youtube_channel: UCSGN02SH4zmdVke-bslh3LA
    youtube_channel_name: TonelliCueto
