title: Ill-said Thoughts
author:
  name: Josué Tonelli-Cueto
  email: josue.tonelli.cueto@bizkaia.eu
description: > # this means to ignore newlines until "show_excerpts:"
  Personal blog of Josué Tonelli-Cueto on random things. In English & Spanish.

show_excerpts: false # set to true to show excerpts on the homepage

comments: true #allows comments!

hyvor:
  id: 4879

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: tonellicueto
  date_format: "%-d/%b/%Y"

  # generate social links in footer
  social_links:
    twitter: tonellicueto
    github: tonellicueto
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: tonellicueto
    linkedin: tonellicueto
    # pinterest: jekyll
    #youtube: tonellicueto
    youtube_channel: UCSGN02SH4zmdVke-bslh3LA
    youtube_channel_name: TonelliCueto
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
